[options]
addons_path = odoo/addons,addons
data_dir = /tmp
admin_passwd = admin123
db_host = ${PGHOST}
db_port = ${PGPORT}
db_user = ${PGUSER}
db_password = ${PGPASSWORD}
db_name = ${PGDATABASE}
without_demo = all
proxy_mode = True
x_sendfile = True
