[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = farisjewelry123  # Set a fixed password for now
db_host = dpg-d496riili9vc739mmk40-a.oregon-postgres.render.com
db_port = 5432
db_user = ${DB_USER}
db_password = ${DB_PASSWORD}
db_name = faris_jewelry
without_demo = all
proxy_mode = True
x_sendfile = True
xmlrpc_port = 10000
http_port = 10000
